### ISSUE TITLE
Oh wow, would you look at that! Unsafe I see?

### ISSUE THREAD

**Issue by AlastorPlayz** [xixoxixo/xixoxixo1#1]
Don't download this. For your own safety, ladies and gentlemen.
![Screenshot 2024-02-16 105727](https://github.com/xixoxixo/xixoxixo1/assets/160259469/b97730a3-0451-4da4-8158-e950633c69ab)

**Comment by Volmin0** [comment]
yo have any way of cracking voicemod pro? plus its so obvious that its a trojan i checked all the java installers

**Comment by AlastorPlayz** [comment]
Yeah, figured it was a trojan. But no, I don't sadly. Really wish I did. Man, voicemod is too pricey.
